### ISSUE TITLE
Announcement blog post error

### ISSUE THREAD

**Issue by kisaragi-hiu** [zyrolasting/kinda-ferpy#10]
The [announcement blog post](https://sagegerard.com/kinda-ferpy-intro.html) of this library has an error in it that makes it seem like `stateful-cell` does the same thing as `make-parameter`:

```racket
(require kinda-ferpy)

(define x (stateful-cell 1))
(define y (stateful-cell 1))
(define sum (stateful-cell (λ _ (+ (x) (y)))))
;; ^ should not have the lambda
```

With the lambda, `sum` would have to be called as `((sum))`, and would have its dependencies updated when `((sum))` is run, not when they are mutated (eg. `(x 5)`).

I wanted to reply to the toot on Fosstodon, but my Mastodon instance errors out, so I figured this is the best place for this report.

**Comment by zyrolasting** [comment]
Thanks muchly. That code block is just outdated. It used to be correct before a breaking change made in response to #2.

**Comment by zyrolasting** [comment]
The post has been updated.
